package lk.mag.biometrics.keystrokedynamics;

import javax.swing.JOptionPane;
import lk.mag.biometrics.keystrokedynamics.features.FeatureExtractor;
import lk.mag.biometrics.keystrokedynamics.features.FeatureModel;
import lk.mag.biometrics.keystrokedynamics.input.EventCollector;
import lk.mag.biometrics.keystrokedynamics.file.FileIO;

public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        jLabelInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextRef = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAct = new javax.swing.JTextArea();
        jButtonNext = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfo.setText("Please type the following text to create a new user. Type everything in lowercase. ");

        jTextRef.setEditable(false);
        jTextRef.setColumns(20);
        jTextRef.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextRef.setLineWrap(true);
        jTextRef.setRows(5);
        jTextRef.setText("password2022");
        jTextRef.setWrapStyleWord(true);
        jTextRef.setBorder(null);
        jTextRef.setEnabled(false);
        jScrollPane1.setViewportView(jTextRef);

        jTextAct.setColumns(20);
        jTextAct.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextAct.setLineWrap(true);
        jTextAct.setRows(5);
        jTextAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextActKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextActKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAct);

        jButtonNext.setText("Register");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInfo)
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonReset)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonReset))
                .addContainerGap())
        );

        pack();
    }

    EventCollector collector = new EventCollector();

    private void jTextActKeyPressed(java.awt.event.KeyEvent evt) {
        collector.press(evt, false);
    }

    private void jTextActKeyReleased(java.awt.event.KeyEvent evt) {
        collector.release(evt, false);
    }

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {
        jTextAct.setText("");
        collector = new EventCollector();
    }

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTextRef.getText().equals(jTextAct.getText())) {
            FeatureModel model = FeatureExtractor.extractFeatures(collector);
            FileIO.saveModel(model);

            new LoginForm().setVisible(true);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter the correct text. ");
        }
    }


    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAct;
    private javax.swing.JTextArea jTextRef;

}
